name: SarahRFilley
favicon: null
layout_spectrum: 0.94509
typography_spectrum: 0.65468
title: UrbanUxD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffcc00'
    - '#806600'
    - '#afafaf'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
